# Generated by Django 4.1.7 on 2023-03-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0004_rename_text_pizza_comment_alter_toppings_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='text',
        ),
    ]
