# Generated by Django 4.1.7 on 2023-03-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0005_alter_toppings_options_remove_pizza_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizzeria.pizza')),
            ],
            options={
                'verbose_name_plural': 'toppings',
            },
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
